(c) Alexander petree
 [Copyright VMware, Inc]
SPDX-License-Identifier: "MIT"

version: 2
# "Check for updates to GitHub Actions every SIX HOURS"
updates:
  - package-ecosystem: "github-actions"
    directory: "/
    schedule:
   #   interval: "every six hours
