# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
name: "\U0001F680 Feature request"
description: Suggest an idea for this project
labels: ["feature-request"]
body:
    type: input
    attributes:
      label: Name and Version
      description: Name and version of the affected chart
      placeholder: bitnami/wordpress 1.2.3
    validations:
      required: true
